#!/bin/bash

task=GAMBLING
run=$1
subj=$2

BASEDIR=`pwd`
cd ..
MAINDATADIR=/s3/hcp
MAINOUTPUTDIR=`pwd`/Analysis
cd $BASEDIR

#replaced RSNmap with 8 mask files from PNAS
for RSNmap in DMN ; do

  OUTPUT=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_nPPI_netTC_${RSNmap}
  DATA=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_Act.feat/filtered_func_data.nii.gz
  NVOLUMES=`fslnvols ${DATA}`

  #checking L1 output
  #comment out sanity check when running full dataset
  #SANITY CHECK
  if [ -e ${OUTPUT}.feat/cluster_mask_zstat14.nii.gz ]; then
    echo "L1_Gam_nPPI_netTC has been run for $subj $run $RSNmap"
    exit
  else
    rm -rf ${OUTPUT}.feat
  fi

  #EV files
  EVDMN=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_Act.feat/DMN_tc.txt
  EVECN=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_Act.feat/ECN_tc.txt
  EVZERO=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_Act.feat/net0000_tc.txt
  EVONE=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_Act.feat/net0001_tc.txt
  EVTWO=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_Act.feat/net0002_tc.txt
  EVFOUR=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_Act.feat/net0004_tc.txt
  EVFIVE=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_Act.feat/net0005_tc.txt
  EVSIX=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_Act.feat/net0006_tc.txt
  EVEIGHT=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_Act.feat/net0008_tc.txt
  EVNINE=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_Act.feat/net0009_tc.txt
  EVWIN=${MAINDATADIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/EVs/win.txt
  EVLOSS=${MAINDATADIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/EVs/loss.txt

  #find and replace: run feat for smoothing
  ITEMPLATE=${BASEDIR}/templates/L1GamnPPI_netTC.fsf
  OTEMPLATE=${MAINOUTPUTDIR}/${subj}/MNINonLinear/Results/tfMRI_${task}_${run}/L1_Gam_nPPI_netTC_${RSNmap}.fsf
  sed -e 's@OUTPUT@'$OUTPUT'@g' \
  -e 's@DATA@'$DATA'@g' \
  -e 's@NVOLUMES@'$NVOLUMES'@g' \
  -e 's@EVDMN@'$EVDMN'@g' \
  -e 's@EVECN@'$EVECN'@g' \
  -e 's@EVZERO@'$EVZERO'@g' \
  -e 's@EVONE@'$EVONE'@g' \
  -e 's@EVTWO@'$EVTWO'@g' \
  -e 's@EVFOUR@'$EVFOUR'@g' \
  -e 's@EVFIVE@'$EVFIVE'@g' \
  -e 's@EVSIX@'$EVSIX'@g' \
  -e 's@EVEIGHT@'$EVEIGHT'@g' \
  -e 's@EVNINE@'$EVNINE'@g' \
  -e 's@EVWIN@'$EVWIN'@g' \
  -e 's@EVLOSS@'$EVLOSS'@g' \
  <$ITEMPLATE> $OTEMPLATE

  #runs feat on output template
  feat $OTEMPLATE

  #delete unused files
  rm -rf ${OUTPUT}.feat/filtered_func_data.nii.gz
  rm -rf ${OUTPUT}.feat/stats/res4d.nii.gz
  rm -rf ${OUTPUT}.feat/stats/corrections.nii.gz
  rm -rf ${OUTPUT}.feat/stats/threshac1.nii.gz
done
